### ISSUE TITLE
MySQL Error 1146

### ISSUE THREAD

**Issue by SdogfromJtown92** [scoringengine/scoringengine#660]
Hey sorry I hope this is the right place to ask for help. The error I am getting when i go to localhost is 1146 Table scoring_engine.settings doesn't exist. Was I suppose to edit a conf file or did something not install right? Any help you can give would be awesome!

**Comment by pwnbus** [comment]
I'm assuming you're installing it manually (not docker), can you confirm that you've run https://scoringengine.readthedocs.io/en/latest/installation/engine.html#setup-scoring-engine-teams-and-services ?

Specifically `/home/engine/scoring_engine/src/bin/setup` which populates the database (which is why you're getting that error)

**Comment by SdogfromJtown92** [comment]
The file was copied, but the bin/setup was not run correctly. Thank you so much for the help!!!
