### ISSUE TITLE
Fix sqlalchemy TimeoutError exceptions

### ISSUE THREAD

**Issue by s-newman** [scoringengine/scoringengine#663]
I guess one of my recent features (#657, #658) broke the database connection in one of the API routes. I and other RIT students have discovered that the web container will now throw `sqlalchemy.exc.TimeoutError` exceptions almost immediately after the competition starts, right after the first requests to the website are made.

I haven't had the time to look at this yet, but I think I'll have a bit of time tomorrow afternoon to take a look.

Screenshot of the tail end of the stack trace from the docker logs:
![bad](https://user-images.githubusercontent.com/25960951/68458699-6efba680-01d1-11ea-8805-d0fb6cababb1.png)

**Comment by RustyBower** [comment]
Ah! I think I know what's happening here.

https://github.com/scoringengine/scoringengine/pull/657/files#diff-604704ecaa66c184dc19b3b9c5f0cfdeR11-R31

I'm _think_ this is opening 10 connection to the DB, which only allows 5 (but can burst to 10 by default) in addition to the initial connection to the DB.

I believe you can fix this here - https://github.com/scoringengine/scoringengine/blob/dab6682d1170fea37483978baff3efebe2b5610c/scoring_engine/db.py#L34 by [increasing the pool size](https://docs.sqlalchemy.org/en/13/core/pooling.html) to something like:

```session = scoped_session(sessionmaker(bind=create_engine(config.db_uri, isolation_level=isolation_level, pool_size=10, max_overflow=10)))```

Give that a shot and let me know if that works, otherwise I'll take a crack at this next week when I'm back home.

**Comment by s-newman** [comment]
Been busy with other things for the past week, but I've got some free time right now. Gonna try out this solution real quick and see if it helps.

**Comment by s-newman** [comment]
It looks like that solved the issue. I'm not sure why that's going on, because the `teams_to_update` list should have been empty when I have encountered this error. :man_shrugging:
