### ISSUE TITLE
pep8

### ISSUE THREAD

**Issue by zmallen** [scoringengine/scoringengine#7]
https://gist.github.com/MichaelCurrie/802ce28c993ff2dd632c might be interesting for Travis

**Comment by pwnbus** [comment]
Instead of having travis ci commit back to the project, I added pycodestyle as a travis ci command which verifies the codebase of pep8 errors. I've excluded a couple errors (Line too long, import statement not at the top), but I think it's worth it.

The build will fail if there are pep8 errors.
https://github.com/pwnbus/scoring_engine/pull/42
